title: SKIP
remote_theme: "mmistakes/jekyll-theme-basically-basic@1.4.5"
url: https://skipgu.github.io/
logo: /assets/icons/logo_skip_small.png
twitter_username: ""
github_username: skipgu
email: skip@gota.gu.se
instagram_username: "skip.gu"
linkedin_username: "company/skip-student-association"
discord_link: "https://tinyurl.com/skip-discord"
google_analytics: G-96M5M9TCM7 

paginate: 10
paginate_path: /page:num/

plugins:
  - jekyll-paginate

collections:
  communityposts:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: "_communityposts"
      type: communityposts
    values:
      layout: posts
      read_time: true
    

