title: SKIP
remote_theme: "mmistakes/jekyll-theme-basically-basic@1.4.5"
url: https://skipgu.github.io/
logo: /assets/icons/logo_skip_small.png
twitter_username: ""
github_username: skipgu
email: skip@gota.gu.se
google_analytics: G-96M5M9TCM7 
